use_frameworks!

platform :ios, '9.0'

target 'RDVTabBarControllerJMLRS_Example' do
  pod 'RDVTabBarControllerJMLRS', :path => '../'

  target 'RDVTabBarControllerJMLRS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
